<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAgjt1pV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAgjt1pV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAgjt1pV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAgjt1pV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAgjt1pV\App_KernelDevDebugContainer([
    'container.build_hash' => 'Agjt1pV',
    'container.build_id' => 'd954262b',
    'container.build_time' => 1653216007,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAgjt1pV');
