<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ50qiL0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ50qiL0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ50qiL0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ50qiL0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ50qiL0\App_KernelDevDebugContainer([
    'container.build_hash' => 'J50qiL0',
    'container.build_id' => '6aa04a96',
    'container.build_time' => 1651481321,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ50qiL0');
